config/routes.rb
ReportGenerator3155::Application.routes.draw do
  root to: "students#index"
  
  get "/caps_:time", to: "codecademy_scraper#process_students", as: "caps", defaults: {time: Time.now.getlocal.strftime("%m-%d-%Y_%H-%M-%S")}
  
  get "/ch4", to: "ch4_walkthrough#index", as: "ch4"
  post "/ch4_:time", to: "ch4_walkthrough#process_students", as: "ch4_report", defaults: {time: Time.now.getlocal.strftime("%m-%d-%Y_%H-%M-%S")}
  
  get "/gitimmersion", to: "gitimmersion#index", as: "gitimmersion"
  post "gitimmersion_:time", to: "gitimmersion#process_students", as: "gitimmersion_report", defaults: {time: Time.now.getlocal.strftime("%m-%d-%Y_%H-%M-%S")}
  
  get "/railstutorial", to: "railstutorial#index", as: "railstutorial"
  post "railstutorial_:time", to: "railstutorial#process_students", as: "railstutorial_report", defaults: {time: Time.now.getlocal.strftime("%m-%d-%Y_%H-%M-%S")}
  resources :students
end

app/models/student.rb
class Student < ActiveRecord::Base
	validate :name, :niner_net, presence: true
	#:name, :niner_net, presence: true
end

app/controllers/students_controller.rb
require 'csv'
class StudentsController < ApplicationController
  def index
    if params[:import] == "students"
      CSV.foreach("/home/ubuntu/workspace/ReportGen/app/assets/Students.csv", :headers => true) do |row|
        Student.create(:canvasID => row['canvasID'], :name => row['name'], :section => row['section'], :SISid => row['SISid'], :niner_net => row['SISlogin'])
      end 
    elsif params[:import] == "cc"
      CSV.foreach("/home/ubuntu/workspace/ReportGen/app/assets/Codecademy.csv", :headers => true) do |row|
        Student.where(:canvasID => row['canvasID']).update_all(:codecademy => row['codeacademy'])
      end
    elsif params[:import] == "github"
      CSV.foreach("/home/ubuntu/workspace/ReportGen/app/assets/Github.csv", :headers => true) do |row|
        Student.where(:canvasID => row['canvasID']).update_all(:github_username=> row['GitHubUsername'])
      end   
    elsif params[:import] == "ch4"
      CSV.foreach("/home/ubuntu/workspace/ReportGen/app/assets/Ch4.csv", :headers => true) do |row|
        Student.where(:canvasID => row['canvasID']).update_all(:ch4_repo_name=> row['ch4Repo'])
      end  
    elsif params[:import] == "rails"
      CSV.foreach("/home/ubuntu/workspace/ReportGen/app/assets/RailsTutorial.csv", :headers => true) do |row|
        Student.where(:canvasID => row['canvasID']).update_all(:RailsTutorialHeroku=> row['herokuURL'])
      end        
    end
    
    if params[:clear]
      Student.delete_all    
    end    
  
    if params[:sort_by]
      @sortUsing = params[:sort_by]
    else
      @sortUsing = "name"
    end
    
    @students = Student.order(@sortUsing, :name) 
    @total_students = Student.count
    @githubCount = Student.where("length(github_username) > 1").count
    @tutorialCount = Student.where("length(RailsTutorialHeroku) > 1").count
    @CodeCadCount = Student.where("length(codecademy) > 1").count
  end
  
  def create
    student = Student.create(student_params)
    flash[:message] = "Student '#{student.name}' was successfully created."
    redirect_to students_path
  end
  
  def new
    @student = Student.new
    @url = students_path
    @method = "post"
    @button_text = "Add Student"
    render :edit
  end
  
  def edit
    @student = Student.find(params[:id])
    @url = student_path(@student)
    @method = "patch"
    @button_text = "Edit Student"
  end
  
  def update
    student = Student.find(params[:id])
    student.update(student_params)
    flash[:message] = "Student '#{student.name}' was successfully updated."
    redirect_to students_path
  end
  
  def destroy
    student = Student.find(params[:id])
    student.destroy
    flash[:message] = "Student '#{student.name}' was successfully deleted."
    redirect_to students_path
  end
  
  private
    def student_params
      params.require(:student).permit(:name, :niner_net, :codecademy, :github_username, :ch4_repo_name, :RailsTutorialHeroku, :canvasID, :SISid, :section)
    end
end

app/views/students/edit.html.haml
= form_for @student do |f|
  = text_input_with_label f, :name, "Name"
  = text_input_with_label f, :niner_net, "NinerNet ID"
  = text_input_with_label f, :codecademy, "Codecademy Username"
  = text_input_with_label f, :github_username, "GitHub Username"
  = text_input_with_label f, :ch4_repo_name, "Chapter 4 Walkthrough Repository Name"
  = text_input_with_label f, :RailsTutorialHeroku, "Hartl Rails Tutorial Heroku URL"
  = text_input_with_label f, :canvasID, "Canvas ID"
  = text_input_with_label f, :SISid, "SISid"
  = text_input_with_label f, :section, "Section"
  .row
    %div{class: "col-md-12"}
      = f.submit @button_text, class: "btn btn-xs btn-primary"

app/views/students/index.html.haml
%div{class: "well"}
  %div

    = link_to("import students", students_path(import: "students"))

    |    
    
    = link_to("import codecademy", students_path(import: "cc"))

    |  
    
    = link_to("import github", students_path(import: "github"))

    | 
    
    = link_to("import walkthrough repo", students_path(import: "ch4"))

    | 
    
    = link_to("import tutorial url", students_path(import: "rails"))

    |     
    
    = link_to(" clear student list", students_path(clear: "yes"))  
    
    |
      
    Number of Students:
    = @students.length
- unless @students.empty?


      
  %table{class: "table table-hover"}
    %thead
      %tr
        %th
        %th      
        %th= link_to("Name", students_path(sort_by: "Name")) 
        %th{:width => "275"}
        %th= link_to("Codecademy #{@CodeCadCount}", students_path(sort_by: "codecademy")) 
        %th= link_to("Hartl Tutorial #{@tutorialCount}", students_path(sort_by: "RailsTutorialHeroku"))    
        %th= link_to("GitHub User #{@githubCount}", students_path(sort_by: "github_username"))         
        %th= link_to("NinerNet ID", students_path(sort_by: "niner_net"))
    %tbody
      - @students.each do |student|
        %tr
          %td
            = link_to '<span class="glyphicon glyphicon-cog"></span>'.html_safe, edit_student_path(student), class: "btn btn-xs btn-success"
          %td
            = form_for student, url: student_path(student), html: {method: "delete"} do |f|
              = content_tag :button, type: :submit, class: "btn btn-xs btn-danger", data: {confirm: "Really delete student '#{student.name}'?"} do
                %span{class: "glyphicon glyphicon-remove"}        
          %td= link_to(student.name, edit_student_path(student))
          %td 
          %td
            - if student.codecademy != nil && student.codecademy != ""
              Yes
          %td 
            - if student.RailsTutorialHeroku != nil && student.RailsTutorialHeroku != ""
              Yes
          %td= student.github_username          
          %td= student.niner_net
          